Mempool:
  IND:
    Capacity: 2097151
    CacheSize: 337
  ETHRX:
    Capacity: 1048575
    CacheSize: 465
    DataroomSize: 2200
  NAME:
    Capacity: 65535
    CacheSize: 255
  HDR:
    Capacity: 65535
    CacheSize: 255
  INTG:
    Capacity: 65535
    CacheSize: 255
  INT:
    Capacity: 65535
    CacheSize: 255
  DATA0:
    Capacity: 65535
    CacheSize: 255
  DATA1:
    Capacity: 255
    CacheSize: 0
    DataroomSize: 9000
LCoreAlloc: null
Face:
  EnableEth: true
  EthDisableRxFlow: false
  EthMtu: 1500
  EthRxqFrames: 4096
  EthTxqPkts: 256
  EthTxqFrames: 4096
  EnableSock: true
  SockTxqPkts: 256
  SockTxqFrames: 1024
  ChanRxgFrames: 4096
Ndt:
  PrefixLen: 2
  IndexBits: 16
  SampleFreq: 8
Fib:
  MaxEntries: 65535
  NBuckets: 256
  StartDepth: 8
Fwdp:
  FwdQueueCapacity: 128
  LatencySampleFreq: 16
  PcctCapacity: 131071
  CsCapMd: 32768
  CsCapMi: 32768
Ping:
  QueueCapacity: 256
